#!/usr/bin/env sh

services="$@"

generate_random_password() {
    < /dev/urandom tr -dc _A-Z-a-z-0-9 | head -c${1:-32};echo;
}

add_service() {
    echo "  -f docker-compose.$1.yml \\" >> docker-laravel
}

if [ -f ".env" ] || [ -f "docker-laravel" ]; then
    echo "Nothing was done, as either a .env or a docker-laravel file already exists"
else
    # Create the `docker-laravel` file

    echo "#!/usr/bin/env sh" > docker-laravel
    echo "docker-compose -f docker-compose.yml \\" >> docker-laravel

    for service in $services
    do
        add_service $service
    done

    echo "\"\$@\"" >> docker-laravel

    chmod +x docker-laravel

    # Create the `.env` file

    echo "APP_URL=http://localhost" > .env
    echo "APP_KEY=" >> .env
    echo "APP_TIMEZONE=UTC" >> .env
    echo "APP_LOCALE=en" >> .env
    echo "APP_FALLBACK_LOCALE=en" >> .env
    echo "APP_BACKUPS_FOLDER=/backups" >> .env

    for service in $services
    do
        if [ "$service" = "basic-auth" ]; then
            echo "" >> .env
            echo "BASIC_AUTH_USERNAME=laravel" >> .env
            echo "BASIC_AUTH_PASSWORD=`generate_random_password`" >> .env
        fi

        if [ "$service" = "redis" ]; then
            echo "" >> .env
            echo "QUEUE_CONNECTION=redis" >> .env
            echo "QUEUE_NAME=default" >> .env
            echo "REDIS_HOST=redis" >> .env
            echo "REDIS_PASSWORD=`generate_random_password`" >> .env
            echo "REDIS_PORT=6379" >> .env
            echo "CACHE_DRIVER=redis" >> .env
        fi

        if [ "$service" = "mailhog" ]; then
            echo "" >> .env
            echo "MAIL_MAILER=smtp" >> .env
            echo "MAIL_HOST=mailhog" >> .env
            echo "MAIL_PORT=1025" >> .env
            echo "MAIL_FROM_NAME=\"\${APP_NAME}\"" >> .env
            echo "MAIL_USERNAME=null" >> .env
            echo "MAIL_PASSWORD=null" >> .env
            echo "MAIL_ENCRYPTION=null" >> .env
        fi

        if [ "$service" = "mariadb" ] || [ "$service" = "mysql" ]; then
            echo "" >> .env
            echo "DB_HOST=$service" >> .env
            echo "DB_DATABASE=laravel" >> .env
            echo "DB_USERNAME=laravel" >> .env
            echo "DB_PASSWORD=`generate_random_password`" >> .env
            echo "DB_ROOT_PASSWORD=`generate_random_password`" >> .env
        fi
    done
fi
