version: '3'
services:
    redis:
        image: 'redis:alpine'
        ports:
            - 6379:6379
        volumes:
            - redis:/data
        networks:
            - laravel
        healthcheck:
            test: redis-cli ping
            retries: 3
            timeout: 5s
        restart: always
networks:
    laravel:
        driver: bridge
volumes:
    redis:
        driver: local