version: '3'
services:
    nginx:
        build:
            context: ./docker-images/nginx
            dockerfile: letsencrypt.Dockerfile
            args:
                LETSENCRYPT_DOMAIN: '${LETSENCRYPT_DOMAIN}'
                LETSENCRYPT_EMAIL: '${LETSENCRYPT_EMAIL}'
        ports:
            - 443:443
        volumes:
            - ./volume/letsencrypt/:/etc/letsencrypt/
