version: '3'
services:
    php:
        depends_on:
            - mysql
    mysql:
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_ROOT_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
        healthcheck:
            retries: 3
            test: mysqladmin ping -u$$MYSQL_USER -p$$MYSQL_PASSWORD
            timeout: 3s
        image: mysql:8.0
        restart: always
        volumes:
            - mysql:/var/lib/mysql
        networks:
            - laravel
networks:
    laravel:
        driver: bridge
volumes:
    mysql:
        driver: local