version: '3'
services:
    core:
        build:
            context: ./docker-images/alpine
            dockerfile: Dockerfile
            target: prod
            args:
                TIMEZONE: ${APP_TIMEZONE}
        entrypoint: ["php-fpm", "-R", "-F"]
        env_file: .env
        healthcheck:
            retries: 3
            test: php-fpm-healthcheck || exit 1
            timeout: 3s
        networks:
            - laravel
        restart: always
        stdin_open: true
        tty: true
        volumes:
            - laravel:/var/www/html
            - ./.env:/var/www/html/.env
            - ./volumes/shared:/shared
            - ./volumes/backups:/var/www/html/storage/backups
        working_dir: /var/www/html
    cron:
        build:
            context: ./docker-images/alpine
            dockerfile: Dockerfile
            target: cron
            args:
                TIMEZONE: ${APP_TIMEZONE}
        env_file: .env
        networks:
            - laravel
        restart: always
        stdin_open: true
        tty: true
        volumes:
            - laravel:/var/www/html
            - ./.env:/var/www/html/.env
            - ./volumes/shared:/shared
        working_dir: /var/www/html
    nginx:
        build:
            context: ./docker-images/nginx
            dockerfile: basic.Dockerfile
        depends_on:
            - core
        env_file: .env
        healthcheck:
            retries: 3
            test: curl -f http://nginx || exit 1
            timeout: 3s
        links:
            - core
        networks:
            - laravel
        ports:
            - 80:80
        restart: always
        volumes:
            - laravel:/var/www/html
            - ./.env:/var/www/html/.env
            - ./volumes/shared:/shared
        working_dir: /var/www/html
networks:
    laravel:
        driver: bridge
volumes:
    laravel: