version: '3'
services:
    supervisor:
        build:
            context: ./docker-images/alpine
            dockerfile: Dockerfile
            target: supervisor
            args:
                TIMEZONE: ${APP_TIMEZONE}
        restart: always
        stdin_open: true
        tty: true
        entrypoint: ["supervisord", "--nodaemon", "--configuration", "/etc/supervisor/supervisord.conf"]
        environment:
            REDIS_HOST:
            REDIS_PASSWORD:
            REDIS_PORT:
            QUEUE_CONNECTION:
            QUEUE_NAME:
            MEMORY_LIMIT: "1024"
        volumes:
            - laravel:/var/www/html
            - ./.env:/var/www/html/.env
        networks:
            - laravel
networks:
    laravel:
        driver: bridge
