version: '3'
services:
    core:
        build:
            context: ./docker-images/alpine
            dockerfile: Dockerfile
            target: dev
    mariadb:
        ports:
            - 3306:3306
networks:
    laravel:
        driver: bridge
