version: '3'
services:
    php:
        build:
            context: ./docker-images/alpine
            dockerfile: Dockerfile
            target: dev
    mysql:
        ports:
            - 3306:3306
networks:
    laravel:
        driver: bridge
