version: '3'
services:
    nginx:
        build:
            context: ./docker-images/nginx
            dockerfile: letsencrypt.Dockerfile
            args:
                letsencrypt_domain: '${LETSENCRYPT_DOMAIN}'
                letsencrypt_email: '${LETSENCRYPT_EMAIL}'
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./:/var/www/html
            - ./volume/letsencrypt/:/etc/letsencrypt/
